export const ADMIN_FIELDS = [
  {
    name: 'MAIN',
    fields: [
      {value: '_id', viewValue: '_id'},
      {value: 'employeeId', viewValue: 'employeeId'},
      {value: 'dialerId', viewValue: 'dialerId'},
      {value: 'firstName', viewValue: 'firstName'},
      {value: 'middleName', viewValue: 'middleName'},
      {value: 'lastName', viewValue: 'lastName'},
      {value: 'gender', viewValue: 'gender'},
      {value: 'socialSecurity', viewValue: 'socialSecurity'},
      {value: 'status', viewValue: 'status'},
    ],
  },
  {
    name: 'COMPANY',
    fields: [
      {value: 'company.client', viewValue: 'client'},
      {value: 'company.campaign', viewValue: 'campaign'},
      {value: 'company.manager', viewValue: 'manager'},
      {value: 'company.shiftManager', viewValue: 'shiftManager'},
      {value: 'company.supervisor', viewValue: 'supervisor'},
      {value: 'company.trainer', viewValue: 'trainer'},
      {value: 'company.branch', viewValue: 'branch'},
      {value: 'company.trainingGroupRef', viewValue: 'trainingGroupRef'},
      {value: 'company.trainingGroupNum', viewValue: 'trainingGroupNum'},
      {value: 'company.hireDate', viewValue: 'hireDate'},
      {value: 'company.terminationDate', viewValue: 'terminationDate'},
      {value: 'company.reapplicant', viewValue: 'reapplicant'},
      {value: 'company.reapplicantTimes', viewValue: 'reapplicantTimes'},
      {value: 'company.bilingual', viewValue: 'bilingual'},
    ],
  },
  {
    name: 'PERSONAL',
    fields: [
      {value: 'personal.maritalStatus', viewValue: 'maritalStatus'},
      {value: 'personal.amountOfChildren', viewValue: 'amountOfChildren'},
      {value: 'personal.address', viewValue: 'address'},
      {value: 'personal.town', viewValue: 'town'},
      {value: 'personal.district', viewValue: 'district'},
      {value: 'personal.addressDate', viewValue: 'addressDate'},
      {value: 'personal.celNumber', viewValue: 'celNumber'},
      {value: 'personal.telNumber', viewValue: 'telNumber'},
      {value: 'personal.birthDate', viewValue: 'birthDate'},
      {value: 'personal.birthPlaceDis', viewValue: 'birthPlaceDis'},
      {value: 'personal.birthPlaceTow', viewValue: 'birthPlaceTow'},
      {value: 'personal.emailAddress', viewValue: 'emailAddress'},
      {value: 'personal.emailDate', viewValue: 'emailDate'},
    ],
  },
  {
    name: 'PAYROLL',
    fields: [
      {value: 'payroll.TIN', viewValue: 'TIN'},
      {value: 'payroll.payrollType', viewValue: 'payrollType'},
      {value: 'payroll.bankName', viewValue: 'bankName'},
      {value: 'payroll.bankAccount', viewValue: 'bankAccount'},
      {value: 'payroll.billable', viewValue: 'billable'},
      {value: 'payroll.paymentType', viewValue: 'paymentType'},
    ],
  },
  {
    name: 'POSITION',
    fields: [
      {value: 'position.0.client', viewValue: 'client'},
      {value: 'position.0.department', viewValue: 'department'},
      {value: 'position.0.positionId', viewValue: 'positionId'},
      {value: 'position.0.name', viewValue: 'name'},
      {value: 'position.0.baseWage', viewValue: 'baseWage'},
      {value: 'position.0.startDate', viewValue: 'startDate'},
      {value: 'position.0.endDate', viewValue: 'endDate'},
    ],
  },
  {
    name: 'SHIFT',
    fields: [
      'shift',
    ],
  },
  {
    name: 'FAMILY & EMERGENCY',
    fields: [
      {value: 'family.referenceName', viewValue: 'referenceName'},
      {value: 'family.relationship', viewValue: 'relationship'},
      {value: 'family.birthDate', viewValue: 'birthDate'},
      {value: 'family.celNumber', viewValue: 'celNumber'},
      {value: 'family.telNumber', viewValue: 'telNumber'},
      {value: 'family.emailAddress', viewValue: 'emailAddress'},
      {value: 'family.address', viewValue: 'address'},
      {value: 'family.emergencyContact', viewValue: 'emergencyContact'},
      {value: 'family.comment', viewValue: 'comment'},
    ],
  },
  {
    name: 'COMMENTS',
    fields: [
      {value: 'reason', viewValue: 'reason'},
      {value: 'comment', viewValue: 'comment'},
      {value: 'commentDate', viewValue: 'commentDate'},
      {value: 'submittedBy', viewValue: 'submittedBy'},
    ],
  },
  {
    name: 'ATTRITION',
    fields: [
      'reason1',
      'reason2',
      'comment',
      'commentDate',
      'submittedBy'
    ],
  },
];
