export const REPORTS = [
  {
    name: 'Restriction Report',
    tooltip: `employeeId, firstName, lastName, actualClient, actualCampaign, celNumber,
    telNumber, email, address, town, district, restriction`,
    projection: 'restriction',
    options: [],
  },
  {
    name: 'Shift Report',
    tooltip: `
     employeeId,
    firstName,
    lastName,
    actualClient,
    actualCampaign,
    celNumber,
    telNumber,
    email,
    address,
    town,
    district,
    restriction,
    shift
    `,
    projection: 'shift',
    options: [],
  },
  {
    name: 'Position Report',
    tooltip: `
    employeeId,
    firstName,
    lastName,
    actualClient,
    actualCampaign,
    manager,
    shiftManager,
    supervisor,
    trainer,
    billable,
    position
    `,
    projection: 'position',
    options: [
      {
        $unwind: {
          path: '$position',
          preserveNullAndEmptyArrays: true,
        },
      },
      {
        $addFields: {
          position: '$position.name',
          department: '$position.department',
          positionClient: '$position.client',
          positionCampaign: '$position.campaign',
          positionId: '$position.positionId',
          startDate: { $dateToString: { date: '$position.startDate', format: '%m/%d/%Y' } },
          endDate: { $dateToString: { date: '$position.endDate', format: '%m/%d/%Y' } },
        },
      },
    ],
  },
  {
    name: 'Leads Report',
    tooltip: `
    employeeId,
    firstName,
    lastName,
    actualClient,
    actualCampaign,
    manager,
    shiftManager,
    supervisor,
    trainer
    `,
    projection: 'leads',
    options: [],
  },
  {
    name: 'Hire Report',
    tooltip: `
     employeeId,
    firstName,
    lastName,
    actualClient,
    actualCampaign,
    hireDate
    `,
    projection: 'hire',
    options: [],
  },
  {
    name: 'Emergency Contact Report',
    tooltip: ` employeeId, firstName, lastName, actualClient, actualCampaign,
              celNumber, telNumber, email, address, town, district, family
              `,
    projection: 'emergency',
    options: [],
  },
];
export const PROJECTIONS = {
  restriction: {
    _id: 0,
    employeeId: 1,
    firstName: 1,
    lastName: 1,
    actualClient: '$company.client',
    actualCampaign: '$company.campaign',
    celNumber: '$personal.celNumber',
    telNumber: '$personal.telNumber',
    email: '$personal.emailAddress',
    address: '$personal.address',
    town: '$personal.town',
    district: '$personal.district',
    restriction: '$personal.restriction',
  },
  emergency: {
    _id: 0,
    employeeId: 1,
    firstName: 1,
    lastName: 1,
    actualClient: '$company.client',
    actualCampaign: '$company.campaign',
    celNumber: '$personal.celNumber',
    telNumber: '$personal.telNumber',
    email: '$personal.emailAddress',
    address: '$personal.address',
    town: '$personal.town',
    district: '$personal.district',
    family: 1,
  },
  shift: {
    _id: 0,
    employeeId: 1,
    firstName: 1,
    lastName: 1,
    actualClient: '$company.client',
    actualCampaign: '$company.campaign',
    celNumber: '$personal.celNumber',
    telNumber: '$personal.telNumber',
    email: '$personal.emailAddress',
    address: '$personal.address',
    town: '$personal.town',
    district: '$personal.district',
    restriction: '$personal.restriction',
    shift: 1,
  },
  position: {
    _id: 0,
    employeeId: 1,
    firstName: 1,
    lastName: 1,
    actualClient: '$company.client',
    actualCampaign: '$company.campaign',
    manager: '$company.manager.name',
    shiftManager: '$company.shiftManager.name',
    supervisor: '$company.supervisor.name',
    trainer: '$company.trainer.name',
    billable: '$payroll.billable',
    position: { $arrayElemAt: ['$position', 0] },
  },
  leads: {
    _id: 0,
    employeeId: 1,
    firstName: 1,
    lastName: 1,
    actualClient: '$company.client',
    actualCampaign: '$company.campaign',
    manager: '$company.manager.name',
    shiftManager: '$company.shiftManager.name',
    supervisor: '$company.supervisor.name',
    trainer: '$company.trainer.name',
  },
  hire: {
    _id: 0,
    employeeId: 1,
    firstName: 1,
    lastName: 1,
    actualClient: '$company.client',
    actualCampaign: '$company.campaign',
    hireDate: { $dateToString: { date: '$company.hireDate', format: '%m/%d/%Y' } },
  },
};
